# Generated by Django 2.2.6 on 2019-12-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myrbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单表', 'verbose_name_plural': '菜单表'},
        ),
    ]
