# Generated by Django 2.2.6 on 2019-12-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrbac', '0002_auto_20191224_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='weight',
            field=models.IntegerField(default=1),
        ),
    ]
