# Generated by Django 2.2.6 on 2019-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrbac', '0004_auto_20191225_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='按钮权限'),
        ),
    ]
